# Mean, Variance, Standard Deviation Calculator

This is a project for a certification on Freecodecamp.org. Check out the readme to see the exact project specifications.

In [1]:
import numpy as np

def calculate(list):
    if len(list) != 9: #loop returns value error is list is not nine numbers long
        raise ValueError("List must contain nine numbers.")
            
    a = np.array(list[0:3])#putting list into arrays
    b = np.array(list[3:6])
    c = np.array(list[6:])
    d = np.array([a, b, c])

    #the following block creates a dictionary, turning the output arrays into lists
    calculations = {"mean" : [d.mean(axis=0).tolist(), d.mean(axis=1).tolist(), d.mean()], 
    "variance" : [d.var(axis=0).tolist(), d.var(axis=1).tolist(), d.var()],
    "standard deviation" : [d.std(axis=0).tolist(), d.std(axis=1).tolist(), d.std()],
    "max" : [d.max(axis=0).tolist(), d.max(axis=1).tolist(), d.max()],
    "min" : [d.min(axis=0).tolist(), d.min(axis=1).tolist(), d.min()],
    "sum" : [d.sum(axis=0).tolist(), d.sum(axis=1).tolist(), d.sum()]}    




    return calculations

In [2]:
my_list = [2,6,2,8,4,0,1,5,7]
calculate(my_list)

{'mean': [[3.6666666666666665, 5.0, 3.0],
  [3.3333333333333335, 4.0, 4.333333333333333],
  3.888888888888889],
 'variance': [[9.555555555555557, 0.6666666666666666, 8.666666666666666],
  [3.555555555555556, 10.666666666666666, 6.222222222222221],
  6.987654320987654],
 'standard deviation': [[3.091206165165235,
   0.816496580927726,
   2.943920288775949],
  [1.8856180831641267, 3.265986323710904, 2.494438257849294],
  2.6434171674156266],
 'max': [[8, 6, 7], [6, 8, 7], 8],
 'min': [[1, 4, 0], [2, 0, 1], 0],
 'sum': [[11, 15, 9], [10, 12, 13], 35]}

In [3]:
listydo = [0,1,2,3,4,5,6,7,8]

a = np.array(listydo[0:3])
b = np.array(listydo[3:6])
c = np.array(listydo[6:])
my_array = np.array([a, b, c])
print(my_array)
print(my_array.sum(axis=0))
print(my_array.sum())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 9 12 15]
36
